version: '3'

services:
  web:
    image: pemrograman-web-2-uas:latest
    container_name: pemrograman-web-2-uas
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: your-mysql-container
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: database_kuliah
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: admin_password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
